### ISSUE TITLE
Seems LFB cause the large clientpermissions.xml, on the extensive repetition of commands.

### ISSUE THREAD

**Issue by esirprus** [evilfactory/Barotrauma-lua-attempt#67] opened 2022-04-25 02:32 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
we can see https://github.com/Regalis11/Barotrauma/issues/8962 and https://github.com/Regalis11/Barotrauma/issues/8933, the server seems all use LFB, and this also happen on my linux server with LFB installed. but i'm not 100% sure, seems server without LFB works good.

**Steps To Reproduce**
(not sure) join a DedicatedServer with LFB, and give you some command. quit and join several times, see how the xml file expands.

**Version**
0.17.12.0  linux with LFB DedicatedServer  [LUA] Lua! Version 5db4be7 

**Additional information**
I uploaded my file to help you.
[clientpermissions.zip](https://github.com/evilfactory/Barotrauma-lua-attempt/files/8551216/clientpermissions.zip)

**Comment by evilfactory** [comment] 2022-04-25 09:29
Not caused by LFB, fixed in base game tho

**Closed by evilfactory** 2022-04-25 09:29 UTC
